In [1]:
import numpy as np
from scipy import signal
import scipy.io as scio
import sys
sys.path.append('src/')
from convnet import cnn
import time

In [65]:
check = np.ones((2,2,3,3))
check[1,0,1,:] = 2
check[1,0,:,2] = 3
check[0,1,2,:] = 5
check[0,1,:,1] = 4
print check
#print np.rot90(check[0],2)
for i in range(check.shape[0]):
    for j in range(check.shape[1]):
        check[i,j] =  np.rot90(check[i,j],2)
print check
# print np.pad(check, 1,'constant')[1:-1]

[[[[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]

  [[ 1.  4.  1.]
   [ 1.  4.  1.]
   [ 5.  4.  5.]]]


 [[[ 1.  1.  3.]
   [ 2.  2.  3.]
   [ 1.  1.  3.]]

  [[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]]]
[[[[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]

  [[ 5.  4.  5.]
   [ 1.  4.  1.]
   [ 1.  4.  1.]]]


 [[[ 3.  1.  1.]
   [ 3.  2.  2.]
   [ 3.  1.  1.]]

  [[ 1.  1.  1.]
   [ 1.  1.  1.]
   [ 1.  1.  1.]]]]


In [67]:
def ch(a):
    return [a*2,a+2]
[pl, che] = ch(3)
print pl
print che

6
5


In [3]:
net = cnn()
mnist = scio.loadmat('data/mnist_big.mat')

In [4]:
inp = mnist['X_train'][1:10]/255.0
inpD = []
for item in inp:
    inpD.append(item.reshape(28, 28))

In [5]:
avg = 0
start = time.time()
for item in inpD:
    check = net.forward(item)
avg += time.time() - start
start = time.time()
for item in inpD:
    check = net.forward(item)
avg += time.time() - start
start = time.time()
for item in inpD:
    check = net.forward(item)
avg += time.time() - start

print avg
print check

0.882935285568
[ 0.09906194  0.09906194  0.09906194  0.1058324   0.09919455  0.10017085
  0.10036422  0.09906194  0.09906194  0.09912829]
